/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SellerRole;

import Business.Books.Author;
import Business.Books.Book;
import Business.Books.Catagory;
import Business.Campaign.BookOfferCampaign;
import Business.Campaign.Campaign;
import Business.Campaign.NewBookCampaign;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CampaignManager;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Minal
 */
public class SellerCreateCampaignPanel extends javax.swing.JPanel {

    /**
     * Creates new form SellerCreateCampaignPanel
     */

   
    private JPanel userProcessContainer;
    private CampaignManager organization;
    private UserAccount account;
    private String filePath;
    private EcoSystem business;
    private Enterprise enterprise;
    SellerCreateCampaignPanel(JPanel userProcessContainer, Organization organization, UserAccount account, EcoSystem business, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.organization=(CampaignManager) organization;
        this.account=account;
        this.business = business;
        this.enterprise=enterprise;
        filePath = null;
        populateComboBoxes();
    }
    
    public void populateComboBoxes() {
        jComboBoxBook.removeAllItems();        
        for (Book c: business.getBd().getListOfBooks()){
            jComboBoxBook.addItem(c.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPromoCode = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblProPic = new javax.swing.JLabel();
        btnUploadImg = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDiscount = new javax.swing.JTextField();
        jComboBoxBook = new javax.swing.JComboBox<>();

        jLabel2.setText("Name:");

        jLabel3.setText("Book");

        jLabel6.setText("Promo Code:");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSave.setText("Add Campaign");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Create Campaign");

        lblProPic.setBackground(new java.awt.Color(204, 204, 255));
        lblProPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProPic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        btnUploadImg.setText("Upload Image");
        btnUploadImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadImgActionPerformed(evt);
            }
        });

        jLabel5.setText("Discount%:");

        jTextFieldDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDiscountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(298, 298, 298)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblProPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUploadImg, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName)
                                    .addComponent(jComboBoxBook, 0, 279, Short.MAX_VALUE)
                                    .addComponent(txtPromoCode)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel1))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProPic, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUploadImg)
                            .addComponent(btnSave)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBoxBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPromoCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(229, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
             userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SellerJPanel CampaignMnagerjp = (SellerJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUploadImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadImgActionPerformed
        // TODO add your handling code here:
        JFileChooser filechooser = new JFileChooser();
        filechooser.showOpenDialog(null);
        File f = filechooser.getSelectedFile();
        filePath = f.getAbsolutePath();
        ImageIcon imgIcon = new ImageIcon(filePath);
        Image imgResized = imgIcon.getImage().getScaledInstance(200, 200,Image.SCALE_DEFAULT );
        ImageIcon imgIconResized = new ImageIcon(imgResized);
        lblProPic.setIcon(imgIconResized);
    }//GEN-LAST:event_btnUploadImgActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try{
        String name = txtName.getText();        
        double discount = Double.valueOf(jTextFieldDiscount.getText());        
        String promoCode = txtPromoCode.getText();
        String bookName = (String) jComboBoxBook.getSelectedItem();
        Book b = null;
        for(Book book:business.getBd().getListOfBooks()){
            if(book.getName() == bookName)
                b=book;
        }        
        if(name == null || discount == 0 || filePath == null || promoCode == null){
            JOptionPane.showMessageDialog(null,"Some Required details are missing and discount should be more than 0 and less than 100","Error", JOptionPane.ERROR_MESSAGE);
        }else if(discount > 100){
            JOptionPane.showMessageDialog(null,"Discount cannot be greater than 100%","Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            BookOfferCampaign campaign = (BookOfferCampaign) organization.getCd().addBookOfferCampaign();
            campaign.setAuthor(b.getAuthor());
            campaign.setBook(b);
            campaign.setCatagory(b.getCatagory());
            campaign.setFilepath(filePath);
            campaign.setName(name);
            campaign.setDiscount(discount);
            campaign.setPromoCode(promoCode);
            campaign.setSellerName(enterprise.getName());
            campaign.setOrganization(organization);
            JOptionPane.showMessageDialog(null, "Campaign successfully added");
        }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Discount should be a number!!");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jTextFieldDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDiscountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUploadImg;
    private javax.swing.JComboBox<String> jComboBoxBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldDiscount;
    private javax.swing.JLabel lblProPic;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPromoCode;
    // End of variables declaration//GEN-END:variables
}
