/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ReaderRole;

import Business.Books.Doners;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.LibraryOrganization;
import Business.Organization.Organization;
import Business.UserAccount.Readers;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LibraryRequest;
import Business.WorkQueue.Message;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bengre
 */
public class AllLibraryRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AllLibraryRequestJPanel
     */
    private JPanel userProcessContainer;
    private Readers account;
    private EcoSystem business;
    AllLibraryRequestJPanel(JPanel userProcessContainer, Readers account, EcoSystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.business=business;
        populateTable();
        btnAccept.setEnabled(false);
        btnReject.setEnabled(false);
    }
    
    private void populateTable(){
        DefaultTableModel modelmes = (DefaultTableModel) tblMessages.getModel();        
        modelmes.setRowCount(0);
        for (WorkRequest wr: account.getWorkQueue().getWorkRequestList()) {
            if(wr instanceof LibraryRequest) {
                if(wr.getStatus() == "New"){
                    Object[] row = new Object[4];
                    row[0] = wr;
                    row[1] = wr.getStatus();
                    row[2] = ((LibraryRequest) wr).getBook();
                    row[3] = ((LibraryRequest) wr).getLibName();
                    modelmes.addRow(row);                     
                    }
            }
        }
    }
    
    private Enterprise getEnterprise(UserAccount r){
        for(Network n: business.getNetworkList()){
                for(Enterprise e: n.getEnterpriseDirectory().getEnterpriseList()){
                    for(Organization o: e.getOrganizationDirectory().getOrganizationList()){                        
                            for(UserAccount ua: o.getUserAccountDirectory().getUserAccountList()){
                                if(ua.equals(r)){
                                    return e;                           
                            }
                        }
                    }
                }
            }
        return null;
    }
    
    private Organization getOrganization(UserAccount r){
        for(Network n: business.getNetworkList()){
                for(Enterprise e: n.getEnterpriseDirectory().getEnterpriseList()){
                    for(Organization o: e.getOrganizationDirectory().getOrganizationList()){                        
                            for(UserAccount ua: o.getUserAccountDirectory().getUserAccountList()){
                                if(ua.equals(r)){
                                    return o;                           
                            }
                        }
                    }
                }
            }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMessages = new javax.swing.JTable();
        btnRespond = new javax.swing.JButton();
        btnAccept = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Messages");

        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblMessages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "From", "Status", "Book", "Library Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblMessages);

        btnRespond.setText("Respond");
        btnRespond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespondActionPerformed(evt);
            }
        });

        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(292, 292, 292)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAccept)
                                .addGap(66, 66, 66)
                                .addComponent(btnReject)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRespond, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRespond)
                    .addComponent(btnAccept)
                    .addComponent(btnReject))
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SeeNotification seeNotification = (SeeNotification) component;
        seeNotification.populateTables();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRespondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespondActionPerformed
        // TODO add your handling code here:
        int selectedRowValue = tblMessages.getSelectedRow();
        if(selectedRowValue >= 0){
            btnAccept.setEnabled(true);
            btnReject.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null,"Please select a Request to Respond");
        }
    }//GEN-LAST:event_btnRespondActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        int selectedRowValue = tblMessages.getSelectedRow();
        if(selectedRowValue >= 0){
            LibraryRequest request = (LibraryRequest)tblMessages.getValueAt(selectedRowValue, 0);
            UserAccount r = (UserAccount) request.getSender();           
            request.setReason("Donated");
            request.setStatus("Accepted");
            Enterprise ent = getEnterprise(r);
            LibraryOrganization libOrg = (LibraryOrganization) getOrganization(r);
            Doners d = libOrg.getDl().addDoners();
            d.setBook(request.getBook());
            d.setName(account.getEmployee().getFirstName() + " " + account.getEmployee().getLastName());
            Message m = (Message) libOrg.getWorkQueue().createMessage();
            m.setSender(account);            
            m.setStatus("New");
            m.setMessageBody(accessibleContext + " has Donated book " + request.getBook().getName() + " to your library!!");            
            btnAccept.setEnabled(false);
            btnReject.setEnabled(false);
            populateTable();
        }
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        int selectedRowValue = tblMessages.getSelectedRow();
        if(selectedRowValue >= 0){
            LibraryRequest request = (LibraryRequest)tblMessages.getValueAt(selectedRowValue, 0);
            UserAccount r = (UserAccount) request.getSender();
            LibraryOrganization libOrg = (LibraryOrganization) getOrganization(r);
            request.setStatus("Rejected");
            String reason = JOptionPane.showInputDialog(null,"Enter your reason for rejection","Reason",JOptionPane.QUESTION_MESSAGE);
            request.setReason(reason);
            btnAccept.setEnabled(false);
            btnReject.setEnabled(false);            
            Message m = (Message) libOrg.getWorkQueue().createMessage();
            m.setSender(account);            
            m.setStatus("New");
            m.setMessageBody(account + " has rejected your request to donate book " + request.getBook().getName() + " to your library and the reason is " + request.getReason());
            populateTable();
        }
    }//GEN-LAST:event_btnRejectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton btnRespond;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblMessages;
    // End of variables declaration//GEN-END:variables
}
