/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ReaderRole;

import Business.Books.Book;
import Business.EcoSystem;
import Business.UserAccount.Readers;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FollowRequest;
import Business.WorkQueue.Message;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Minal
 */
public class SeeNotification extends javax.swing.JPanel {

    /**
     * Creates new form SeeNotification
     */
    
    private JPanel userProcessContainer;
    private Readers account;   
    private EcoSystem business;
    public SeeNotification(JPanel userProcessContainer, Readers account, EcoSystem business) {
        initComponents();
        this.account=account;
        this.userProcessContainer=userProcessContainer;
        this.business=business;
        populateTables();
        btnAccept.setEnabled(false);
        btnFollowBack.setEnabled(false);
        btnReject.setEnabled(false);
    }
    
    public void populateTables(){
        DefaultTableModel modelnot = (DefaultTableModel) tblNotifications.getModel();
        DefaultTableModel modelmes = (DefaultTableModel) tblMessages.getModel();

        modelnot.setRowCount(0);
        modelmes.setRowCount(0);
        for (WorkRequest wr: account.getWorkQueue().getWorkRequestList()) {
            if("New".equals(wr.getStatus())){
            Object[] row = new Object[2];
            row[0] = wr;
            row[1] = wr.getStatus();
            if(wr instanceof Message)                
                modelmes.addRow(row);
            if(wr instanceof FollowRequest)
                modelnot.addRow(row);            
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNotifications = new javax.swing.JTable();
        btnAccept = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        btnFollowBack = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnRespond = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMessages = new javax.swing.JTable();
        jButtonReadRespond = new javax.swing.JButton();
        jButtonMarkRead = new javax.swing.JButton();
        jButtonViewMessages = new javax.swing.JButton();
        jButtonViewLibReq = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Notifications");

        tblNotifications.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "From", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblNotifications);

        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        btnFollowBack.setText("Follow Back");
        btnFollowBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFollowBackActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRespond.setText("Respond");
        btnRespond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespondActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Follow Requests");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Messages");

        tblMessages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "From", "Status"
            }
        ));
        jScrollPane2.setViewportView(tblMessages);

        jButtonReadRespond.setText("Read and Respond");
        jButtonReadRespond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReadRespondActionPerformed(evt);
            }
        });

        jButtonMarkRead.setText("Mark as Read");
        jButtonMarkRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMarkReadActionPerformed(evt);
            }
        });

        jButtonViewMessages.setText("View All Messages");
        jButtonViewMessages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewMessagesActionPerformed(evt);
            }
        });

        jButtonViewLibReq.setText("View Library Requests");
        jButtonViewLibReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewLibReqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(151, 151, 151))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(272, 272, 272)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnAccept)
                        .addGap(42, 42, 42)
                        .addComponent(btnReject)
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRespond, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFollowBack, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonMarkRead, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(jButtonViewMessages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonViewLibReq, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonReadRespond, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRespond)
                    .addComponent(jButtonReadRespond)
                    .addComponent(jButtonMarkRead))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccept)
                    .addComponent(btnReject)
                    .addComponent(btnFollowBack)
                    .addComponent(jButtonViewMessages)
                    .addComponent(jButtonViewLibReq))
                .addContainerGap(184, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        int selectedRowValue = tblNotifications.getSelectedRow();
        if(selectedRowValue >= 0){
            FollowRequest request = (FollowRequest)tblNotifications.getValueAt(selectedRowValue, 0);
            Readers r = (Readers) request.getSender();
            r.addFollower(account);
            account.addFollower();
            request.setResponse("Accepted");
            request.setStatus("Responded");
            Message m = (Message) r.getWorkQueue().createMessage();
            m.setSender(account);
            m.setReceiver(r);
            m.setStatus("New");
            m.setMessageBody(account + " Accepted your Follow Request");
            btnFollowBack.setEnabled(true);
            btnAccept.setEnabled(false);            
            btnReject.setEnabled(false);
            JOptionPane.showMessageDialog(null,"Follow Request Accepted");
        }
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRespondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespondActionPerformed
        // TODO add your handling code here:        
        int selectedRowValue = tblNotifications.getSelectedRow();
        if(selectedRowValue >= 0){
            btnAccept.setEnabled(true);        
            btnReject.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null,"Please select a Request to Respond");
        }
    }//GEN-LAST:event_btnRespondActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        int selectedRowValue = tblNotifications.getSelectedRow();
        if(selectedRowValue >= 0){
            FollowRequest request = (FollowRequest)tblNotifications.getValueAt(selectedRowValue, 0);
            request.setResponse("Rejected");
            request.setStatus("Responded");
            btnAccept.setEnabled(false);            
            btnReject.setEnabled(false);
            Readers r = (Readers) request.getSender();
            Message m = (Message) r.getWorkQueue().createMessage();
            m.setSender(account);
            m.setReceiver(r);
            m.setStatus("New");
            m.setMessageBody(account + " Rejected your Follow Request");
            populateTables();
        }
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnFollowBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFollowBackActionPerformed
        // TODO add your handling code here:
        int selectedRowValue = tblNotifications.getSelectedRow();
        if(selectedRowValue >= 0){
            FollowRequest request = (FollowRequest)tblNotifications.getValueAt(selectedRowValue, 0);
            Readers r = (Readers) request.getSender();
            FollowRequest fr = (FollowRequest) r.getWorkQueue().createFollowRequest();
            fr.setSender(account);
            fr.setReceiver(r);
            fr.setStatus("New");
            fr.setResponse("Pending");
            btnFollowBack.setEnabled(false);
            JOptionPane.showMessageDialog(null,"Follow Request Sent!!");
            populateTables();
            btnAccept.setEnabled(false);
            btnFollowBack.setEnabled(false);
            btnReject.setEnabled(false);
        }
    }//GEN-LAST:event_btnFollowBackActionPerformed

    private void jButtonMarkReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMarkReadActionPerformed
        // TODO add your handling code here:
        int selectedRowValue = tblNotifications.getSelectedRow();
        if(selectedRowValue >= 0){
            Message request = (Message)tblNotifications.getValueAt(selectedRowValue, 0);
            request.setStatus("Read");
            populateTables();
        }else{
            JOptionPane.showMessageDialog(null,"Please select a Message");
        }
    }//GEN-LAST:event_jButtonMarkReadActionPerformed

    private void jButtonViewMessagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewMessagesActionPerformed
        // TODO add your handling code here:
        AllMessageJPanel allMessageJPanel = new AllMessageJPanel(userProcessContainer, account);
        userProcessContainer.add("AllMessageJPanel", allMessageJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButtonViewMessagesActionPerformed

    private void jButtonReadRespondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReadRespondActionPerformed
        // TODO add your handling code here:
        int selectedRowValue = tblMessages.getSelectedRow();
        if(selectedRowValue >= 0){
            Message request = (Message)tblMessages.getValueAt(selectedRowValue, 0);
            MessagesJPanel messagesJPanel = new MessagesJPanel(userProcessContainer, account,request,true);
            userProcessContainer.add("MessagesJPanel", messagesJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }else{
            JOptionPane.showMessageDialog(null,"Please select a Message");
        }
        
    }//GEN-LAST:event_jButtonReadRespondActionPerformed

    private void jButtonViewLibReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewLibReqActionPerformed
        // TODO add your handling code here:
        AllLibraryRequestJPanel allLibraryRequestJPanel = new AllLibraryRequestJPanel(userProcessContainer, account,business);
        userProcessContainer.add("AllLibraryRequestJPanel", allLibraryRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButtonViewLibReqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFollowBack;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton btnRespond;
    private javax.swing.JButton jButtonMarkRead;
    private javax.swing.JButton jButtonReadRespond;
    private javax.swing.JButton jButtonViewLibReq;
    private javax.swing.JButton jButtonViewMessages;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblMessages;
    private javax.swing.JTable tblNotifications;
    // End of variables declaration//GEN-END:variables
}
