/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AuthorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.Readers;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Minal
 */
public class AuthorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AuthorJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private Organization organization;
    private Enterprise enterprise;
    private Readers account;

    public AuthorJPanel(JPanel userProcessContainer, EcoSystem business, Organization organization, Enterprise enterprise, UserAccount account) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account = (Readers) account;
        this.business=business;
        this.organization=organization;
        this.enterprise=enterprise;
        jLabelUserName.setText(this.account.getEmployee().getFirstName() + " " + this.account.getEmployee().getLastName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jButtonMessages = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Author Work Area");

        jLabelUserName.setText("Name");

        jButtonMessages.setText("Respond to Readers");
        jButtonMessages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMessagesActionPerformed(evt);
            }
        });

        jButton2.setText("View My Books");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonMessages, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(327, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelUserName)
                .addGap(41, 41, 41)
                .addComponent(jButtonMessages)
                .addGap(80, 80, 80)
                .addComponent(jButton2)
                .addContainerGap(338, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMessagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMessagesActionPerformed
        // TODO add your handling code here:
        AuthorAllMessageJPanel authorAllMessageJPanel = new AuthorAllMessageJPanel(userProcessContainer, account);
        userProcessContainer.add("AuthorAllMessageJPanel", authorAllMessageJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButtonMessagesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AuthorBooksJPanel authorBooksJPanel = new AuthorBooksJPanel(userProcessContainer, account,business);
        userProcessContainer.add("AuthorBooksJPanel", authorBooksJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonMessages;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelUserName;
    // End of variables declaration//GEN-END:variables
}
